CREATE TABLE IF NOT EXISTS car (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    car_number VARCHAR(50) NOT NULL UNIQUE,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    car_type VARCHAR(50) NOT NULL,          -- SEDAN, SUV, LUXURY, COMPACT, VAN
    fuel_type VARCHAR(50) NOT NULL,         -- PETROL, DIESEL, HYBRID, ELECTRIC
    seating_capacity INT NOT NULL,
    daily_price DOUBLE NOT NULL,
    status VARCHAR(50) DEFAULT 'AVAILABLE'  -- AVAILABLE, RENTED, UNDER_MAINTENANCE
    );